export const SET_ALIVEPAGE = 'SET_ALIVEPAGE';
export const DELETE_ALIVEPAGE = 'DELETE_ALIVEPAGE';
export const GET_ALLMESSAGE = 'GET_ALLMESSAGE';
export const GET_APPLYMESSAGE = 'GET_APPLYMESSAGE';
export const GET_APPROVEMESSAGE = 'GET_APPROVEMESSAGE';